class Whoop(object):

    disqus         = '''<div id="disqus_thread"></div><script type="text/javascript">var disqus_shortname = 'blogfy_';(function() {var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);})();</script><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript><a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>'''

    sitemap        = '<?xml version="1.0" encoding="{0}" ?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"><!-- Generated by Blogfy https://github.com/wifiextender/blogfy -->{1}</urlset>'

    sidebar        = '<aside id="sidebar"><ul><li class="block"><div class="sidebar-top"></div><div class="sidebar-content">{0}</div><div class="sidebar-bottom"></div></li></ul></aside>'

    git_script     = '<script src="{0}css/js/jquery.min.js" type="text/javascript"></script><script src="{0}css/js/github.js" type="text/javascript"></script><script type="text/javascript">$(function() {1}</script>'

    post_body      = '<h1>{0}</h1><br /><div class="date-left">{1}</div><div class="posted-by">Posted by {2}</div><div class="articleline2"></div>'

    front_pagi     = '<div class="page-navigation cf"><div class="nav-previous"><a href="{0}page/1/">Older Entries</a></div></div>'

    older_newer    = '<div class="page-navigation cf"><div class="nav-next"><a href="{0}">Newer Entries</a></div><div class="nav-previous"><a href="{1}">Older Entries</a></div></div>'

    sitemap_loc    = '<url><loc>{0}</loc><lastmod>{1}</lastmod><priority>0.5</priority></url>'

    font_link      = '<a style="font-size:{0}px" href="{1}tags/{2}/">{2}</a>&nbsp;'

    span           = '<span>{0}</span>&nbsp;<a href="{1}">{2}</a><br />'

    tags_sidebar   = '<h4 class="heading">Tags</h4><!-- tags_body -->'

    recent_sidebar = '<h4 class="heading">Recent Posts</h4><ul><!-- recent_posts --></ul>'

    github_sidebar = '<h4 class="heading">GitHub Repos</h4><div id="github-projects"></div>'

    last_page      = '<div class="nav-previous"><a href="{0}">Older Entries</a></div>'

    atom           = '''<?xml version="1.0" encoding="{0}"?><feed xmlns="http://www.w3.org/2005/Atom"><title><![CDATA[{1}]]></title><link href="{2}atom.xml" rel="self"/><link href="{2}"/><updated>{3}</updated><id>{2}</id><author><name><![CDATA[{4}]]></name></author><generator uri="https://github.com/wifiextender/blogfy">Blogfy</generator>{5}</feed>'''

    atom_entries   = '''<entry><title type="html"><![CDATA[{0}]]></title><link href="{1}"/><updated>{2}</updated><id>{1}</id><content type="html"><![CDATA[{3}<br /><a href="{1}">Read more</a>]]></content></entry>'''