addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - time
      - g++-4.8
language: node_js
node_js:
- "5.0"
env:
  - CXX=g++-4.8 chromeBinaryPath=/home/travis/build/samccone/drool/chrome-linux/chrome
before_install:
- make brotli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip
script:
- make all
